name=${project.artifactId}
version=${project.version}

# Platform Requirements
openmrs.version=>=2.4.0

# Required Backend Modules (OMODs)
omod.fhir2=>=1.8.0
omod.webservices.rest=>=2.42.0
omod.initializer=>=2.5.2
omod.o3forms=>=2.2.0
omod.ugandaemr=>=4.0.0

# Required Frontend Modules (ESMs)
esm.@openmrs/esm-patient-chart-app=>=8.1.0
esm.@openmrs/esm-form-engine-app=>=2.0.0